using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FFTAICommunicationLib
{
    public enum FFTAICommunicationV2DriverInterfaceOperationMode
    {
        //-------------------------------- CAN Node Configuration (0x00) -----------------------------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_CAN_NODE_SELECTION = 0x00000101,
        //-------------------------------- CAN Node Configuration (0x00) -----------------------------------

        //-------------------------------- CAN Node Control (0x1A) -----------------------------------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_CAN_NODE_ENABLE = 0x1A000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_CAN_NODE_DISABLE = 0x1A000102,
        //-------------------------------- CAN Node Control (0xA0) -----------------------------------------

        //-------------------------------- Motor Driver Control (0x1B) -------------------------------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_DRIVER_ENABLE = 0x1B000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_DRIVER_DISABLE = 0x1B000102,
        //-------------------------------- Motor Driver Control (0xB0) -------------------------------------

        //-------------------------------- Device Control and Status Objects (0x03) ------------------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_MODE_OF_OPERATION = 0x03000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_MODE_OF_OPERATION = 0x03000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_CONTROL_WORD = 0x03000102,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_CONTROL_WORD = 0x03000102,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_STATUS_WORD = 0x03000103,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_ERROR_CODE = 0x03000104,
        //-------------------------------- Device Control and Status Objects (0x03) ------------------------

        //-------------------------------- Basic Amplifier Configuration Objects (0x05) --------------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_DEVICE_TYPE = 0x05000101,
        //-------------------------------- Basic Amplifier Configuration Objects (0x05) --------------------

        //-------------------------------- Basic Motor Configuration Objects (0x06) ------------------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_MOTOR_TYPE = 0x06000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_MOTOR_TYPE = 0x06000102,
        //-------------------------------- Basic Motor Configuration Objects (0x06) ------------------------

        //-------------------------------- Real-time Amplifier and Motor Status Objects (0x07) -------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_HIGH_VOLTAGE_REFERENCE = 0x07000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_AMPLIFIER_TEMPERATURE = 0x07000102,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_SYSTEM_TIME = 0x07000103,
        //-------------------------------- Real-time Amplifier and Motor Status Objects (0x07) -------------

        //-------------------------------- Digital I/O Configuration Objects (0x08) ------------------------

        //-------------------------------- Digital I/O Configuration Objects (0x08) ------------------------

        //-------------------------------- Position Loop Configuration Objects (0x09) ----------------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_MOTION_PROFILE_TYPE = 0x09000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_MOTION_PROFILE_TYPE = 0x09000101,

        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_TARGET_POSITION = 0x09000201,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_TARGET_POSITION = 0x09000201,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_PROFILE_VELOCITY = 0x09000202,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_PROFILE_VELOCITY = 0x09000202,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_PROFILE_ACCELERATION = 0x09000203,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_PROFILE_ACCELERATION = 0x09000203,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_PROFILE_DECELERATION = 0x09000204,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_PROFILE_DECELERATION = 0x09000204,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_QUICK_STOP_DECELERATION = 0x09000205,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_QUICK_STOP_DECELERATION = 0x09000205,

        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_ACTUAL_MOTOR_POSITION = 0x09001001,
        //-------------------------------- Position Loop Configuration Objects (0x09) ----------------------

        //-------------------------------- Velocity Loop Configuration Objects (0x0A) ----------------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_MAXIMUM_PROFILE_VELOCITY = 0x0A000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_MAXIMUM_PROFILE_VELOCITY = 0x0A000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_VELOCITY_LOOP_MAXIMUM_ACCELERATION = 0x0A000102,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_VELOCITY_LOOP_MAXIMUM_ACCELERATION = 0x0A000102,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_VELOCITY_LOOP_MAXIMUM_DECELERATION = 0x0A000103,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_VELOCITY_LOOP_MAXIMUM_DECELERATION = 0x0A000103,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_TARGET_VELOCITY = 0x0A000104,

        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_ACTUAL_MOTOR_VELOCITY = 0x0A001001,
        //-------------------------------- Velocity Loop Configuration Objects (0x0A) ----------------------

        //-------------------------------- Current Loop Configuration Objects (0x0B) -----------------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_COMMANDED_CURRENT = 0x0B000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_LIMITED_CURRENT = 0x0B000102,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_ACTUAL_MOTOR_CURRENT = 0x0B001001,
        //-------------------------------- Current Loop Configuration Objects (0x0B) -----------------------

        //-------------------------------- Profile Current Configuration Objects (0x0C) --------------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_TARGET_TORQUE = 0x0C000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_TARGET_TORQUE = 0x0C000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_MAXIMUM_TORQUE = 0x0C000102,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_MAXIMUM_TORQUE = 0x0C000102,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_MAXIMUM_CURRENT = 0x0C000103,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_MAXIMUM_CURRENT = 0x0C000103,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_TORQUE_DEMAND = 0x0C000104,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_MOTOR_RATED_CURRENT = 0x0C000105,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_MOTOR_RATED_CURRENT = 0x0C000105,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_MOTOR_RATED_TORQUE = 0x0C000106,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_MOTOR_RATED_TORQUE = 0x0C000106,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_TORQUE_ACTUAL_VALUE = 0x0C000107,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_CURRENT_ACTUAL_VALUE = 0x0C000108,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_POSITIVE_TORQUE_LIMIT = 0x0C000109,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_POSITIVE_TORQUE_LIMIT = 0x0C000109,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_NEGATIVE_TORQUE_LIMIT = 0x0C00010A,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_NEGATIVE_TORQUE_LIMIT = 0x0C00010A,
        //-------------------------------- Profile Current Configuration Objects (0x0C) --------------------

        //-------------------------------- Homing Mode Operation Objects (0x0E) ----------------------------
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_HOMING_METHOD = 0x0E000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_HOMING_METHOD = 0x0E000101,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_HOMING_VELOCITYS_HOME_VELOCITY_FAST = 0x0E000102,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_HOMING_VELOCITYS_HOME_VELOCITY_FAST = 0x0E000102,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_HOMING_VELOCITYS_HOME_VELOCITY_SLOW = 0x0E000103,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_HOMING_VELOCITYS_HOME_VELOCITY_SLOW = 0x0E000103,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_HOMING_ACCELERATION = 0x0E000104,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_HOMING_ACCELERATION = 0x0E000104,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_HOME_OFFSET = 0x0E000105,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_HOME_OFFSET = 0x0E000105,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_GET_HOME_CONFIG = 0x0E000106,
        MODE_OF_OPERATION_OF_COMMUNICATION_V2_DRIVER_INTERFACE_SET_HOME_CONFIG = 0x0E000106,
        //-------------------------------- Homing Mode Operation Objects (0x0E) ----------------------------
    };
}
